server:
  port: 12001

spring:
  application:
    name: ai-admin-system
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: ai-admin-system-secret-key-2024
  expiration: 86400

logging:
  level:
    com.ai.admin: debug
    root: info